name: Qodana
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  qodana:
    runs-on: windows-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
        with:
          TEST: true
          PACK: true
      - name: Qodana cloud Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      #- name: Qodana Code Scan 
       # uses: github/codeql-action/upload-sarif@v2
        #with:
         # sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json  

      #- name: SonarCloud Scan
       # uses: SonarSource/sonarcloud-github-action@master
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet --version
          dotnet tool restore
          .\sonarcloud.ps1 -sonarSecret ${{ secrets.SONAR_TOKEN }}

